### ISSUE TITLE
Allow user defined add-ons to be used for add-on testing

### ISSUE THREAD

**Issue by erikvold** [AndreasMadsen/steer#1]
This module looks like it could be usefule for either extension developers that want to write tests for their google chrome extensions, or for web devs that want to test how their site looks with certain add-ons installed, like ad-blocking add-ons for example.

Anyhow it looks like it would only be a small change to allow one to install extra add-ons in the steered browser.  I'll have a patch up in a few mins.

**Comment by AndreasMadsen** [comment]
sounds good, lets take the discussion in the PR.
